# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.


# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"
port: 8081

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
     start_tag: '[%'
     end_tag:   '%]'

# configuration file mentioning the list of zookeepers
zookeeper_ensembles: zkensembles.ini

# Your application details
appname: "zoopark"
appabstract: 'A Glance at ZooKeeper Cluster(s)'
appauthor: Nikhil Mulley
appversion: 0.01
appauthoremail: mnikhil<at>gmail.com
